apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: secrethub-mutating-webhook
  labels:
    app: secrethub-mutating-webhook
    kind: mutator
webhooks:
- name: secrethub-mutating-webhook.default.svc.cluster.local
  clientConfig:
    url: "YOUR_CLOUD_FUNCTION_URL"
    caBundle: ""
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  failurePolicy: Fail
