on:
  push:
    branches:
      - release/v*

jobs:
  bump-version:
    name: Bump app info version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bump version in Go code
        uses: florisvdg/action-version-bump@v0.1.0
        with:
          sed: 's/^\(const version = "\).*\("\)$/\1$VERSION\2/g'
          file: app_info.go
          author_email: bender.github@secrethub.io
      - name: Bump version in AWS Lambda and Google Cloud Function README
        uses: florisvdg/action-version-bump@v0.1.0
        with:
          sed: 's/\(source = \(.*\)\?ref=v\).*\("\)$/\1$VERSION\3/g'
          file: deploy/aws-lambda/README.md deploy/gcloud-function/README.md
          author_email: bender.github@secrethub.io
      - name: Bump version in Terraform variables
        uses: florisvdg/action-version-bump@v0.1.0
        with:
          sed: 's/^\(  default = "\).*\("\)$/\1$VERSION\2/g'
          file: deploy/aws-lambda/version.tf deploy/gcloud-function/version.tf
          author_email: bender.github@secrethub.io
